# -*- coding: utf-8 -*-
"""
Created on Tue Feb 11 16:35:48 2020

@author: Jacob
"""

from tkinter import *

root = Tk()
#Creating a Label Widget
myLabel1 = Label(root, text="MISC")
myLabel2 = Label(root, text="SPORTS")
myLabel3 = Label(root, text="Rutgers Tidbits")
myLabel4 = Label(root, text="ISE Department")
myLabel5 = Label(root, text="Flora and Fauna")
myLabel6 = Label(root, text="Crayola Colors")
#Shoving it onto the screen
myLabel1.grid(row=0, column=0)
myLabel2.grid(row=0, column=1)
myLabel3.grid(row=0, column=2)
myLabel4.grid(row=0, column=3)
myLabel5.grid(row=0, column=4)
myLabel6.grid(row=0, column=5)

button1 = Button(root, text="  1  ")
button2 = Button(root, text="  1  ")
button3 = Button(root, text="  1  ")
button4 = Button(root, text="  1  ")
button5 = Button(root, text="  1  ")
button6 = Button(root, text="  1  ")
button7 = Button(root, text="  2  ")
button8 = Button(root, text="  2  ")
button9 = Button(root, text="  2  ")
button10 = Button(root, text="  2  ")
button11 = Button(root, text="  2  ")
button12 = Button(root, text="  2  ")
button13 = Button(root, text="  3  ")
button14 = Button(root, text="  3  ")
button15 = Button(root, text="  3  ")
button16 = Button(root, text="  3  ")
button17 = Button(root, text="  3  ")
button18 = Button(root, text="  3  ")
button19 = Button(root, text="  4  ")
button20 = Button(root, text="  4  ")
button21 = Button(root, text="  4  ")
button22 = Button(root, text="  4  ")
button23 = Button(root, text="  4  ")
button24 = Button(root, text="  4  ")
button25 = Button(root, text="  5  ")
button26 = Button(root, text="  5  ")
button27 = Button(root, text="  5  ")
button28 = Button(root, text="  5  ")
button29 = Button(root, text="  5  ")
button30 = Button(root, text="  5  ")
button31 = Button(root, text="  6  ")
button32 = Button(root, text="  6  ")
button33 = Button(root, text="  6  ")
button34 = Button(root, text="  6  ")
button35 = Button(root, text="  6  ")
button36 = Button(root, text="  6  ")
button37 = Button(root, text="  7  ")
button38 = Button(root, text="  7  ")
button39 = Button(root, text="  7  ")
button40 = Button(root, text="  7  ")
button41 = Button(root, text="  7  ")
button42 = Button(root, text="  7  ")
button43 = Button(root, text="  8  ")
button44 = Button(root, text="  8  ")
button45 = Button(root, text="  8  ")
button46 = Button(root, text="  8  ")
button47 = Button(root, text="  8  ")
button48 = Button(root, text="  8  ")
button49 = Button(root, text="  9  ")
button50 = Button(root, text="  9  ")
button51 = Button(root, text="  9  ")
button52 = Button(root, text="  9  ")
button53 = Button(root, text="  9  ")
button54 = Button(root, text="  9  ")
button55 = Button(root, text="  10 ")
button56 = Button(root, text="  10 ")
button57 = Button(root, text="  10 ")
button58 = Button(root, text="  10 ")
button59 = Button(root, text="  10 ")
button60 = Button(root, text="  10 ")






button1.grid(row=1, column=0)
button2.grid(row=1, column=1)
button3.grid(row=1, column=2)
button4.grid(row=1, column=3)
button5.grid(row=1, column=4)
button6.grid(row=1, column=5)
button7.grid(row=2, column=0)
button8.grid(row=2, column=1)
button9.grid(row=2, column=2)
button10.grid(row=2, column=3)
button11.grid(row=2, column=4)
button12.grid(row=2, column=5)
button13.grid(row=3, column=0)
button14.grid(row=3, column=1)
button15.grid(row=3, column=2)
button16.grid(row=3, column=3)
button17.grid(row=3, column=4)
button18.grid(row=3, column=5)
button19.grid(row=4, column=0)
button20.grid(row=4, column=1)
button21.grid(row=4, column=2)
button22.grid(row=4, column=3)
button23.grid(row=4, column=4)
button24.grid(row=4, column=5)
button25.grid(row=5, column=0)
button26.grid(row=5, column=1)
button27.grid(row=5, column=2)
button28.grid(row=5, column=3)
button29.grid(row=5, column=4)
button30.grid(row=5, column=5)
button31.grid(row=6, column=0)
button32.grid(row=6, column=1)
button33.grid(row=6, column=2)
button34.grid(row=6, column=3)
button35.grid(row=6, column=4)
button36.grid(row=6, column=5)
button37.grid(row=7, column=0)
button38.grid(row=7, column=1)
button39.grid(row=7, column=2)
button40.grid(row=7, column=3)
button41.grid(row=7, column=4)
button42.grid(row=7, column=5)
button43.grid(row=8, column=0)
button44.grid(row=8, column=1)
button45.grid(row=8, column=2)
button46.grid(row=8, column=3)
button47.grid(row=8, column=4)
button48.grid(row=8, column=5)
button49.grid(row=9, column=0)
button50.grid(row=9, column=1)
button51.grid(row=9, column=2)
button52.grid(row=9, column=3)
button53.grid(row=9, column=4)
button54.grid(row=9, column=5)
button55.grid(row=10, column=0)
button56.grid(row=10, column=1)
button57.grid(row=10, column=2)
button58.grid(row=10, column=3)
button59.grid(row=10, column=4)
button60.grid(row=10, column=5)


root.mainloop()